apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: painter
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: ko://github.com/n3wscott/k8s-meetup-atlanta/cmd/painter
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: colors
spec:
  broker: default
  filter:
    attributes:
      type: com.n3wscott.atlanta.mixed-colors
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: painter
      namespace: default