apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: bind-colors
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: colors
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sockeye