name: Publish

on:
  push:
    branches: ['serving-start']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.4
      - run: ko publish ./cmd/colors/ -B -t "start"

